import { useMemo, useState } from 'react'
import { useFinanceAdminInviteMutations, useFinanceAdmins } from '../../hooks/useAdmin.js'
import './AdminSection.css'
import './AdminAdministrators.css'

const EMPTY_INVITES = []

export default function FinanceAdminInvites() {
  const { data: response, isLoading, isError } = useFinanceAdmins(); const mutations = useFinanceAdminInviteMutations(); const data = response?.data; const invites = data?.invites || EMPTY_INVITES; const [share, setShare] = useState(null); const [search, setSearch] = useState(''); const [status, setStatus] = useState('ALL')
  const visible = useMemo(() => invites.filter(invite => `${invite.name || ''} ${invite.email || ''}`.toLowerCase().includes(search.trim().toLowerCase()) && (status === 'ALL' || invite.status === status)), [invites, search, status])
  const showLink = invite => setShare(`${window.location.origin}/adminFin/register?invite=${invite.registrationToken}`)
  const create = () => mutations.create.mutate(undefined, { onSuccess: result => showLink(result.data.data) })
  const refresh = id => mutations.refreshLink.mutate(`${id}/link`, { onSuccess: result => showLink(result.data.data) })
  return <details className="admin-admin-disclosure" open><summary>Administradores financieros <span>{data?.total ?? 0} activos · {invites.length} enlaces</span></summary><section className="admin-marketing-accounts"><div className="admin-section-toolbar"><div><strong>Cuentas de administrador financiero</strong><p>Gestiona las cuentas que procesan pagos y retiros.</p></div><button onClick={create} disabled={isLoading || isError || mutations.create.isPending}>Crear enlace de registro</button></div>{isError && <p className="admin-marketing-error">No se pudieron cargar las invitaciones financieras.</p>}<p className="admin-marketing-help">El administrador financiero gestionará las solicitudes de pago a restaurantes.</p>{share && <div className="admin-marketing-share"><label>Enlace financiero listo para compartir</label><input readOnly value={share} onFocus={event => event.target.select()}/><button onClick={() => navigator.clipboard?.writeText(share)}>Copiar enlace</button></div>}<div className="admin-account-filters"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar por nombre o correo…"/><select value={status} onChange={event => setStatus(event.target.value)}><option value="ALL">Todas</option><option value="APPROVED">Activas / aprobadas</option><option value="SUSPENDED">Suspendidas</option><option value="PENDING">Pendientes</option></select></div><div className="admin-marketing-invites">{visible.length === 0 ? <p>No hay cuentas con estos filtros.</p> : visible.map(invite => <article key={invite.id}><div><strong>{invite.email || 'Enlace de registro financiero'}</strong><span className={`admin-marketing-status admin-marketing-status--${invite.status.toLowerCase()}`}>{invite.status === 'SUSPENDED' ? 'Suspendida' : invite.isFinanceAdmin ? 'Cuenta activa' : 'Aprobada; esperando registro'}</span><small>{invite.accountCreated ? `Cuenta Auth0 creada${invite.name ? ` por ${invite.name}` : ''}` : invite.tokenActive ? 'Enlace activo; aún no se ha registrado' : 'Enlace vencido o pendiente de renovar'}</small><small>Creado: {new Date(invite.createdAt).toLocaleString('es-PE')}</small></div><div className="admin-marketing-actions">{!invite.isFinanceAdmin && invite.status === 'APPROVED' && <button onClick={() => refresh(invite.id)}>{invite.tokenActive ? 'Renovar enlace' : 'Generar enlace'}</button>}{invite.status !== 'APPROVED' && <button onClick={() => mutations.approve.mutate(`${invite.id}/approve`)}>Aprobar / reactivar</button>}{invite.status !== 'SUSPENDED' && <button className="admin-marketing-suspend" onClick={() => mutations.suspend.mutate(`${invite.id}/suspend`)}>Suspender</button>}</div></article>)}</div></section></details>
}
