import { useState } from 'react'
import { useTechAdminInviteMutations, useTechAdmins } from '../../hooks/useAdmin.js'
import './AdminSection.css'
import './AdminAdministrators.css'
export default function TechAdminInvites() {
  const { data: response, isLoading, isError } = useTechAdmins(); const mutations = useTechAdminInviteMutations(); const data = response?.data; const [share, setShare] = useState(null); const invites = data?.invites || []
  const showLink = invite => setShare({ id: invite.id, url: `${window.location.origin}/adminTec/register?invite=${invite.registrationToken}` })
  const create = () => mutations.create.mutate(undefined, { onSuccess: result => showLink(result.data.data) })
  const refresh = id => mutations.refreshLink.mutate(`${id}/link`, { onSuccess: result => showLink(result.data.data) })
  const approve = id => mutations.approve.mutate(`${id}/approve`)
  const suspend = id => mutations.suspend.mutate(`${id}/suspend`)
  return <div className="admin-section"><section className="admin-marketing-accounts"><div className="admin-section-toolbar"><div><strong>Cuentas de administrador técnico</strong><p>{data?.total ?? 0} cuentas activas · {data?.slotsUsed ?? 0} enlaces creados</p></div><button onClick={create} disabled={isLoading || isError || mutations.create.isPending}>Crear enlace de registro</button></div>{isError && <p className="admin-marketing-error">No se pudieron cargar las invitaciones técnicas.</p>}<p className="admin-marketing-help">Comparte el enlace con el técnico. Podrá crear o iniciar sesión con Auth0. El enlace vence en 7 días.</p>{share && <div className="admin-marketing-share"><label>Enlace listo para compartir</label><input readOnly value={share.url} onFocus={event => event.target.select()}/><button onClick={() => navigator.clipboard?.writeText(share.url)}>Copiar enlace</button></div>}<div className="admin-marketing-invites">{invites.length === 0 ? <p>Todavía no se han creado enlaces técnicos.</p> : invites.map(invite => <article key={invite.id}><div><strong>{invite.email || 'Enlace de registro técnico'}</strong><span className={`admin-marketing-status admin-marketing-status--${invite.status.toLowerCase()}`}>{invite.status === 'SUSPENDED' ? 'Suspendida' : invite.isTechAdmin ? 'Cuenta activa' : 'Aprobada; esperando registro'}</span><small>{invite.accountCreated ? `Cuenta Auth0 creada${invite.name ? ` por ${invite.name}` : ''}` : invite.tokenActive ? 'Enlace activo; aún no se ha registrado' : 'Enlace vencido o pendiente de renovar'}</small><small>Creado: {new Date(invite.createdAt).toLocaleString('es-PE')}</small></div><div className="admin-marketing-actions">{!invite.isTechAdmin && invite.status === 'APPROVED' && <button onClick={() => refresh(invite.id)} disabled={mutations.refreshLink.isPending}>{invite.tokenActive ? 'Renovar enlace' : 'Generar enlace'}</button>}{invite.status !== 'APPROVED' && <button onClick={() => approve(invite.id)}>Aprobar / reactivar</button>}{invite.status !== 'SUSPENDED' && <button className="admin-marketing-suspend" onClick={() => suspend(invite.id)}>Suspender</button>}</div></article>)}</div></section></div>
}
