import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useAuth0 } from '@auth0/auth0-react'
import { api, setAuthToken } from '../config/api.js'
import toast from 'react-hot-toast'
const auth = async getAccessTokenSilently => { const token = await getAccessTokenSilently({ authorizationParams: { audience: import.meta.env.VITE_AUTH0_AUDIENCE } }); setAuthToken(token) }
export function useMyReports() { const { isAuthenticated, getAccessTokenSilently } = useAuth0(); return useQuery({ queryKey: ['reports', 'mine'], queryFn: async () => { await auth(getAccessTokenSilently); return (await api.get('/api/v1/reports/mine')).data.data }, enabled: isAuthenticated }) }
export function useCreateReport() { const { getAccessTokenSilently } = useAuth0(); const qc = useQueryClient(); return useMutation({ mutationFn: async payload => { await auth(getAccessTokenSilently); return api.post('/api/v1/reports', payload) }, onSuccess: () => { toast.success('Reporte enviado. Te responderemos en un plazo de 24 horas.'); qc.invalidateQueries({ queryKey: ['reports', 'mine'] }) }, onError: err => toast.error(err?.response?.data?.message || 'No se pudo enviar el reporte') }) }
export function useTechReports(filters) { const { isAuthenticated, getAccessTokenSilently } = useAuth0(); return useQuery({ queryKey: ['tech-reports', filters], queryFn: async () => { await auth(getAccessTokenSilently); return (await api.get('/api/v1/reports', { params: filters })).data.data }, enabled: isAuthenticated, placeholderData: prev => prev, refetchInterval: false, refetchOnWindowFocus: false }) }
export function useAnswerReport() { const { getAccessTokenSilently } = useAuth0(); const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, response, status }) => { await auth(getAccessTokenSilently); return api.patch(`/api/v1/reports/${id}/answer`, { response, status }) }, onSuccess: () => { toast.success('Respuesta guardada'); qc.invalidateQueries({ queryKey: ['tech-reports'] }) }, onError: err => toast.error(err?.response?.data?.message || 'No se pudo guardar la respuesta') }) }
